// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Project URL",
            "url": "https://github.com/valerius21/gitignore.lol"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/valerius21/gitignore.lol/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/list": {
            "get": {
                "description": "Returns a list of all available .gitignore templates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Get available templates",
                "responses": {
                    "200": {
                        "description": "List of available templates",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/{templateList}": {
            "get": {
                "description": "Returns combined .gitignore file for specified templates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Get gitignore templates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of templates (e.g., go,node,python)",
                        "name": "templateList",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Combined .gitignore file content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Template not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "gitignore.lol",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "gitignore.lol API",
	Description:      "A service to generate .gitignore files for your projects. An implementation insprired by the previously known gitignore.io.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
