basePath: /
definitions:
  pkg_server.ErrorResponse:
    properties:
      error:
        description: Error message
        example: Template not found
        type: string
    type: object
  pkg_server.TemplateResponse:
    properties:
      files:
        description: List of available gitignore templates
        example:
        - '["go"'
        - '"node"'
        - '"python"]'
        items:
          type: string
        type: array
    type: object
host: localhost:4444
info:
  contact: {}
  description: A service to generate .gitignore files for your projects. An implementation
    inspired by the previously known gitignore.io.
  license:
    name: MIT
    url: https://github.com/valerius21/gitignore.lol/blob/main/LICENSE
  title: gitignore.lol API
  version: "1.0"
paths:
  /api/{templateList}:
    get:
      description: Returns combined .gitignore file for specified templates
      parameters:
      - description: Comma-separated list of templates (e.g., go,node,python)
        in: path
        name: templateList
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Combined .gitignore file content
          schema:
            type: string
        "400":
          description: Template not found
          schema:
            $ref: '#/definitions/pkg_server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/pkg_server.ErrorResponse'
      summary: Get gitignore templates
      tags:
      - templates
  /api/list:
    get:
      description: Returns a list of all available .gitignore templates
      produces:
      - application/json
      responses:
        "200":
          description: List of available templates
          schema:
            $ref: '#/definitions/pkg_server.TemplateResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/pkg_server.ErrorResponse'
      summary: List available templates
      tags:
      - templates
schemes:
- http
swagger: "2.0"
